### ISSUE TITLE
Issue with training CIFAR 3pxnet model

### ISSUE THREAD

**Issue by ando2097** [nanocad-lab/3pxnet#4] opened 2021-07-27 10:15 UTC
#Issue with training CIFAR 3pxnet

Ran into the following error whilst training a CIFAR model and was hoping that it could be checked before I run the training process again

---

Traceback (most recent call last):
  File "C:\Users\andre\source\repos\3pxnet\3pxnet-training\main_conv.py", line 289, in <module>
    main()
  File "C:\Users\andre\source\repos\3pxnet\3pxnet-training\main_conv.py", line 269, in main
    re = net(testdata)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\andre\source\repos\3pxnet\3pxnet-training\network.py", line 423, in forward
    x = self.conv1(x)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\andre\source\repos\3pxnet\3pxnet-training\binarized_modules.py", line 137, in forward
    out = nn.functional.conv2d(input, self.weight, None, self.stride,
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[100, 32, 5, 34] to have 3 channels, but got 32 channels instead
make: *** [Makefile:13: train] Error 1

---

**Comment by jianshitansuantong233** [comment] 2021-07-28 07:13
Hi, could you tell me which dataset are you training on? And did you make any changes to any source code? Thanks

**Comment by ando2097** [comment] 2021-07-28 07:51
I used the command:

make CIFAR =1 train

no changes have been made to the source code

**Comment by jianshitansuantong233** [comment] 2021-08-10 02:40
Hi ando,
Sorry for the late reply. It should be fixed now. The problem is that previously the Makefile chose a wrong dataset.

**Comment by ando2097** [comment] 2021-08-13 11:19
Error during: make CIFAR =1 train

---

Terminal produces error on windows then continues with permuting.

---


Epoch: [24]     Loss 0.2136 (0.2697)    Prec@1 94.886 (92.071)  Prec@5 100.000 (99.262)
Permuting BinarizeConv2d(3, 128, kernel_size=(3, 3), stride=(1, 1), bias=False)
Traceback (most recent call last):
  File "C:\Users\andre\source\repos\3pxnet\3pxnet-training\utils_own.py", line 242, in permute_all_weights_once
    mod.permute_list[0] = one_time_permute(weight_flat, mod.thres, pack=pack, weight_grad_gpu = grad_flat)    
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BinarizeConv2d' object has no attribute 'thres'

**Closed as completed** 2021-08-13 16:06 UTC
